# Aseprite
# Builds w/
# Chromium graphics library
# Distributed
name: ＡＢＣＤ
on:
  workflow_dispatch:
jobs:
  abcd:
    runs-on: windows-latest
    steps:
      - name: CO
        uses: actions/checkout@v2
        with:
          ref: change-the-title
      - name: CO₂
        shell: bash
        run: |
          export SKIAVERSION="$(curl https://api.github.com/repos/aseprite/skia/releases/latest | jq -r .tag_name)"
          export VERSION="$(curl https://api.github.com/repos/aseprite/aseprite/releases/latest | jq -r .tag_name)"
          echo $SKIAVERSION, $VERSION; mkdir -p a b c; cd a
          curl -LO "https://github.com/aseprite/aseprite/releases/download/$VERSION/Aseprite-$VERSION-Source.zip"
          ls -l; unzip -oq Aseprite-$VERSION-Source.zip
          cd ../c
          curl -OL "https://github.com/aseprite/skia/releases/download/$SKIAVERSION/Skia-Windows-Release-x86.zip"
          ls -l; unzip -qo Skia-Windows-Release-x86.zip
          cd ../b
          # Aseprite不支持在Windows上用g++编译。PATH中的MinGW会干扰CMake判断，又找不到对应的Chocolatey包来卸，故以暴力手段处理。
          for i in c++ cpp gcc g++ cc ar as ld nm ranlib strip windres readelf ld.bfd ld.gold gcc-nm gcc-ar gfortran gcov gdb gprof make mingw32-make ccache
          do
            while rm -v $(which $i)
            do
              :
            done
          done
          mkdir -p "aseprite-$VERSION-dev/data/extensions"
          for i in $(curl https://api.github.com/repos/J-11/Aseprite-Simplified-Chinese/releases/latest | jq -r .assets[].browser_download_url)
          do
            echo Bundling extension: $i
            curl -Lo e.zip $i
            unzip -o e.zip -d "aseprite-$VERSION-dev/data/extensions"
          done
          cat <<'EOF' > "aseprite-$VERSION-dev/aseprite.ini"
            [general]
            language = sChinese
            [theme]
            selected = aseprite-theme-pixel
          EOF
          cat <<'EOF' > b.bat
            for /f "usebackq delims=" %%i in (`vswhere.exe -latest -property installationPath`) do call "%%i\VC\Auxiliary\Build\vcvars32.bat"
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia ^
              -DSKIA_DIR=..\c -DSKIA_LIBRARY_DIR=..\c\out\Release-x86 -DSKIA_LIBRARY=..\c\out\Release-x86\skia.lib ^
              -G Ninja ..\a
            ninja aseprite
          EOF
          cmd.exe /c b.bat
          mv bin/aseprite.exe bin/data "aseprite-$VERSION-dev"
          7z a -psalenzo ../d.7z "aseprite-$VERSION-dev"
          cd ..
          mv d.7z docs
          git add docs/d.7z
          git -c user.email=alice@example.com -c user.name=Alice commit --allow-empty-message -m ""
          git push
